In [1]:
!pip install fcd

Requirement already satisfied: fcd in /Users/stefanhangler/opt/anaconda3/envs/DLNN1/lib/python3.10/site-packages (1.2.2)
Requirement already satisfied: rdkit in /Users/stefanhangler/opt/anaconda3/envs/DLNN1/lib/python3.10/site-packages (from fcd) (2023.9.6)
Requirement already satisfied: scipy in /Users/stefanhangler/opt/anaconda3/envs/DLNN1/lib/python3.10/site-packages (from fcd) (1.9.3)
Requirement already satisfied: torch in /Users/stefanhangler/opt/anaconda3/envs/DLNN1/lib/python3.10/site-packages (from fcd) (2.2.1)
Requirement already satisfied: numpy in /Users/stefanhangler/opt/anaconda3/envs/DLNN1/lib/python3.10/site-packages (from fcd) (1.23.3)
Requirement already satisfied: Pillow in /Users/stefanhangler/opt/anaconda3/envs/DLNN1/lib/python3.10/site-packages (from rdkit->fcd) (9.2.0)
Requirement already satisfied: filelock in /Users/stefanhangler/opt/anaconda3/envs/DLNN1/lib/python3.10/site-packages (from torch->fcd) (3.13.1)
Requirement already satisfied: typing-extensions>=4.8.0 in /Users/stefanhangler/opt/anaconda3/envs/DLNN1/lib/python3.10/site-packages (from torch->fcd) (4.12.2)
Requirement already satisfied: sympy in /Users/stefanhangler/opt/anaconda3/envs/DLNN1/lib/python3.10/site-packages (from torch->fcd) (1.12)
Requirement already satisfied: networkx in /Users/stefanhangler/opt/anaconda3/envs/DLNN1/lib/python3.10/site-packages (from torch->fcd) (3.1)
Requirement already satisfied: jinja2 in /Users/stefanhangler/opt/anaconda3/envs/DLNN1/lib/python3.10/site-packages (from torch->fcd) (3.0.3)
Requirement already satisfied: fsspec in /Users/stefanhangler/opt/anaconda3/envs/DLNN1/lib/python3.10/site-packages (from torch->fcd) (2024.6.1)
Requirement already satisfied: MarkupSafe>=2.0 in /Users/stefanhangler/opt/anaconda3/envs/DLNN1/lib/python3.10/site-packages (from jinja2->torch->fcd) (2.1.1)
Requirement already satisfied: mpmath>=0.19 in /Users/stefanhangler/opt/anaconda3/envs/DLNN1/lib/python3.10/site-packages (from sympy->torch->fcd) (1.3.0)

In [1]:
from guacamol.evaluate_guacamol import evaluate_guacamol

In [11]:
# load csv
import pandas as pd

data = pd.read_csv('./guacamol/data/train_valid_test_guacamol.csv')
# print columns of data
print(data.columns)

Index(['smiles', 'atoms', 'coords', 'partition', 'source_collection'], dtype='object')

In [5]:
import pandas as pd

training_smiles_path = "data/train_guacamol.smiles"

# load train_guacamol.smiles of type smiles
with open(training_smiles_path, 'r') as file:
        smiles = file.readlines()
    # Remove newline characters

training_smiles = [s.strip() for s in smiles]

In [6]:
print(training_smiles[:5])

['CCC(C)(C)Br', 'CCCN(CCc1cccc(-c2ccccc2)c1)C(=O)C1OC(C(=O)O)=CC(N)C1NC(C)=O', 'Oc1ccc(C2CC(c3ccccc3)=NN2C(=S)Nc2ccccc2)cc1', 'CC1(C)OCC2OC3(C4OC(C)(C)OC4CO)OC(C)(C)OC3C2O1', 'COC(=O)c1cc(C(=CCCCC(=O)SC)c2cc(Cl)c(OC)c(C(=O)OC)c2)cc(Cl)c1OC']

In [2]:
#"guacamol model": "generated_smiles/guacamol_model_generated_mols.csv",

path_list = {
        "grande closed": "generated_smiles/grande_closed_generated_mols.csv",
        "coati2": "generated_smiles/coati2_generated_mols.csv",
        "autoreg only": "generated_smiles/autoreg_only_generated_mols.csv",
    }

for model_name, path in path_list.items():
    with open(path, 'r') as f:
        generated_smiles = f.readlines()
    
    if model_name != "guacamol model":
        training_smiles = None

    evaluate_guacamol(generated_smiles, training_smiles, model_name=model_name)

Either training_smiles_path or reference_dataset_path must be provided to calculate FCD.
Validity: 0.9943
Novelty: nan
Uniqueness: 0.8283
FCD Score: nan
FCD GuacaMol: nan
Either training_smiles_path or reference_dataset_path must be provided to calculate FCD.
Validity: 0.8833
Novelty: nan
Uniqueness: 0.9998
FCD Score: nan
FCD GuacaMol: nan
Either training_smiles_path or reference_dataset_path must be provided to calculate FCD.
Validity: 0.9993
Novelty: nan
Uniqueness: 0.0004
FCD Score: nan
FCD GuacaMol: nan

# Analyse Results

In [63]:
import pandas as pd
results = pd.read_csv("./linear_regression_suite/results/coati_linear_probing.csv")
results

,Dataset,Seed,Analysis Type,Model,AUROC Score,AUROC std,RMSE,Spearman,avgp,avgp_std,davgp,davgp_std
0,ames,0,Classification,Barlow Closed (Text),0.716956,0.007467,NaN,NaN,0.700366,0.009978,0.151190,0.006749
1,ames,0,Classification,Grande Closed (Text),0.682680,0.007573,NaN,NaN,0.673720,0.009531,0.124544,0.006607
2,ames,0,Classification,CLAMP,0.743715,0.007206,NaN,NaN,0.720499,0.009556,0.171323,0.006810
3,ames,0,Classification,coati2,0.744065,0.007250,NaN,NaN,0.721438,0.008904,0.172262,0.006390
4,ames,1,Classification,Barlow Closed (Text),0.698516,0.007720,NaN,NaN,0.685105,0.009864,0.136328,0.006472
...,...,...,...,...,...,...,...,...,...,...,...,...
1043,half_life_obach,8,Regression,coati2,NaN,NaN,NaN,0.221459,NaN,NaN,NaN,NaN
1044,half_life_obach,9,Regression,Barlow Closed (Text),NaN,NaN,NaN,0.183688,NaN,NaN,NaN,NaN
1045,half_life_obach,9,Regression,Grande Closed (Text),NaN,NaN,NaN,0.203125,NaN,NaN,NaN,NaN
1046,half_life_obach,9,Regression,CLAMP,NaN,NaN,NaN,0.311776,NaN,NaN,NaN,NaN
1047,half_life_obach,9,Regression,coati2,NaN,NaN,NaN,0.209550,NaN,NaN,NaN,NaN

In [20]:
import numpy as np

def highlight_max(data):
    attr = 'background-color: yellow'
    is_max = data == data.max()
    return [attr if v else '' for v in is_max]

In [25]:
grouped_df = results.groupby(['Dataset', 'Model']).mean(numeric_only=True).reset_index()
# drop column seed
grouped_df = grouped_df.drop(columns=['Seed'])

# store grouped_df in a csv file
grouped_df.to_csv("coati_linear_probing_grouped.csv", index=False)

# Store Combined Results as HTML

In [26]:
# Combine all HTML contents into one HTML file
html_output = '<html><head><style>table {border-collapse: collapse; width: 100%;} th, td {border: 1px solid black; padding: 8px; text-align: left;}</style></head><body>'

for name, group in grouped_df.groupby('Dataset'):
    styled = group.style.apply(highlight_max, subset=['AUROC Score','RMSE','Spearman','avgp','davgp']).render()
    html_output += f'<h1>{name}</h1>{styled}'

html_output += '</body></html>'

# Save the combined HTML to a file
with open('combined_results.html', 'w') as file:
    file.write(html_output)

/var/folders/h5/sfz06yh5207339s992l9zwc80000gn/T/ipykernel_8039/2439730504.py:5: FutureWarning: this method is deprecated in favour of `Styler.to_html()`
  styled = group.style.apply(highlight_max, subset=['AUROC Score','RMSE','Spearman','avgp','davgp']).render()
/var/folders/h5/sfz06yh5207339s992l9zwc80000gn/T/ipykernel_8039/2439730504.py:5: FutureWarning: this method is deprecated in favour of `Styler.to_html()`
  styled = group.style.apply(highlight_max, subset=['AUROC Score','RMSE','Spearman','avgp','davgp']).render()
/var/folders/h5/sfz06yh5207339s992l9zwc80000gn/T/ipykernel_8039/2439730504.py:5: FutureWarning: this method is deprecated in favour of `Styler.to_html()`
  styled = group.style.apply(highlight_max, subset=['AUROC Score','RMSE','Spearman','avgp','davgp']).render()
/var/folders/h5/sfz06yh5207339s992l9zwc80000gn/T/ipykernel_8039/2439730504.py:5: FutureWarning: this method is deprecated in favour of `Styler.to_html()`
  styled = group.style.apply(highlight_max, subset=['AUROC Score','RMSE','Spearman','avgp','davgp']).render()
/var/folders/h5/sfz06yh5207339s992l9zwc80000gn/T/ipykernel_8039/2439730504.py:5: FutureWarning: this method is deprecated in favour of `Styler.to_html()`
  styled = group.style.apply(highlight_max, subset=['AUROC Score','RMSE','Spearman','avgp','davgp']).render()
/var/folders/h5/sfz06yh5207339s992l9zwc80000gn/T/ipykernel_8039/2439730504.py:5: FutureWarning: this method is deprecated in favour of `Styler.to_html()`
  styled = group.style.apply(highlight_max, subset=['AUROC Score','RMSE','Spearman','avgp','davgp']).render()
/var/folders/h5/sfz06yh5207339s992l9zwc80000gn/T/ipykernel_8039/2439730504.py:5: FutureWarning: this method is deprecated in favour of `Styler.to_html()`
  styled = group.style.apply(highlight_max, subset=['AUROC Score','RMSE','Spearman','avgp','davgp']).render()
/var/folders/h5/sfz06yh5207339s992l9zwc80000gn/T/ipykernel_8039/2439730504.py:5: FutureWarning: this method is deprecated in favour of `Styler.to_html()`
  styled = group.style.apply(highlight_max, subset=['AUROC Score','RMSE','Spearman','avgp','davgp']).render()
/var/folders/h5/sfz06yh5207339s992l9zwc80000gn/T/ipykernel_8039/2439730504.py:5: FutureWarning: this method is deprecated in favour of `Styler.to_html()`
  styled = group.style.apply(highlight_max, subset=['AUROC Score','RMSE','Spearman','avgp','davgp']).render()
/var/folders/h5/sfz06yh5207339s992l9zwc80000gn/T/ipykernel_8039/2439730504.py:5: FutureWarning: this method is deprecated in favour of `Styler.to_html()`
  styled = group.style.apply(highlight_max, subset=['AUROC Score','RMSE','Spearman','avgp','davgp']).render()
/var/folders/h5/sfz06yh5207339s992l9zwc80000gn/T/ipykernel_8039/2439730504.py:5: FutureWarning: this method is deprecated in favour of `Styler.to_html()`
  styled = group.style.apply(highlight_max, subset=['AUROC Score','RMSE','Spearman','avgp','davgp']).render()
/var/folders/h5/sfz06yh5207339s992l9zwc80000gn/T/ipykernel_8039/2439730504.py:5: FutureWarning: this method is deprecated in favour of `Styler.to_html()`
  styled = group.style.apply(highlight_max, subset=['AUROC Score','RMSE','Spearman','avgp','davgp']).render()
/var/folders/h5/sfz06yh5207339s992l9zwc80000gn/T/ipykernel_8039/2439730504.py:5: FutureWarning: this method is deprecated in favour of `Styler.to_html()`
  styled = group.style.apply(highlight_max, subset=['AUROC Score','RMSE','Spearman','avgp','davgp']).render()
/var/folders/h5/sfz06yh5207339s992l9zwc80000gn/T/ipykernel_8039/2439730504.py:5: FutureWarning: this method is deprecated in favour of `Styler.to_html()`
  styled = group.style.apply(highlight_max, subset=['AUROC Score','RMSE','Spearman','avgp','davgp']).render()
/var/folders/h5/sfz06yh5207339s992l9zwc80000gn/T/ipykernel_8039/2439730504.py:5: FutureWarning: this method is deprecated in favour of `Styler.to_html()`
  styled = group.style.apply(highlight_max, subset=['AUROC Score','RMSE','Spearman','avgp','davgp']).render()
/var/folders/h5/sfz06yh5207339s992l9zwc80000gn/T/ipykernel_8039/2439730504.py:5: FutureWarning: this method is deprecated in favour of `Styler.to_html()`
  styled = group.style.apply(highlight_max, subset=['AUROC Score','RMSE','Spearman','avgp','davgp']).render()
/var/folders/h5/sfz06yh5207339s992l9zwc80000gn/T/ipykernel_8039/2439730504.py:5: FutureWarning: this method is deprecated in favour of `Styler.to_html()`
  styled = group.style.apply(highlight_max, subset=['AUROC Score','RMSE','Spearman','avgp','davgp']).render()
/var/folders/h5/sfz06yh5207339s992l9zwc80000gn/T/ipykernel_8039/2439730504.py:5: FutureWarning: this method is deprecated in favour of `Styler.to_html()`
  styled = group.style.apply(highlight_max, subset=['AUROC Score','RMSE','Spearman','avgp','davgp']).render()
/var/folders/h5/sfz06yh5207339s992l9zwc80000gn/T/ipykernel_8039/2439730504.py:5: FutureWarning: this method is deprecated in favour of `Styler.to_html()`
  styled = group.style.apply(highlight_max, subset=['AUROC Score','RMSE','Spearman','avgp','davgp']).render()
/var/folders/h5/sfz06yh5207339s992l9zwc80000gn/T/ipykernel_8039/2439730504.py:5: FutureWarning: this method is deprecated in favour of `Styler.to_html()`
  styled = group.style.apply(highlight_max, subset=['AUROC Score','RMSE','Spearman','avgp','davgp']).render()
/var/folders/h5/sfz06yh5207339s992l9zwc80000gn/T/ipykernel_8039/2439730504.py:5: FutureWarning: this method is deprecated in favour of `Styler.to_html()`
  styled = group.style.apply(highlight_max, subset=['AUROC Score','RMSE','Spearman','avgp','davgp']).render()

In [27]:
# add a column rank_auroc to the grouped_df
grouped_df['rank_auroc'] = grouped_df.groupby('Dataset')['AUROC Score'].rank(ascending=False)
grouped_df

,Dataset,Model,AUROC Score,AUROC std,RMSE,Spearman,avgp,avgp_std,davgp,davgp_std,rank_auroc
0,ames,Autoreg Only,0.622710,0.007784,NaN,NaN,0.617710,0.009906,0.077425,0.005897,5.0
1,ames,Barlow Closed (Text),0.705771,0.007628,NaN,NaN,0.682496,0.009607,0.142211,0.006744,3.0
2,ames,CLAMP,0.729509,0.007313,NaN,NaN,0.702198,0.009492,0.161914,0.007049,1.0
3,ames,Grande Closed (Text),0.664600,0.007736,NaN,NaN,0.649511,0.009716,0.109226,0.006399,4.0
4,ames,coati2,0.729429,0.007428,NaN,NaN,0.699742,0.009315,0.159458,0.006912,2.0
...,...,...,...,...,...,...,...,...,...,...,...
99,vdss_lombardo,Autoreg Only,NaN,NaN,NaN,0.131986,NaN,NaN,NaN,NaN,NaN
100,vdss_lombardo,Barlow Closed (Text),NaN,NaN,NaN,0.344879,NaN,NaN,NaN,NaN,NaN
101,vdss_lombardo,CLAMP,NaN,NaN,NaN,0.504836,NaN,NaN,NaN,NaN,NaN
102,vdss_lombardo,Grande Closed (Text),NaN,NaN,NaN,0.397382,NaN,NaN,NaN,NaN,NaN
103,vdss_lombardo,coati2,NaN,NaN,NaN,0.454551,NaN,NaN,NaN,NaN,NaN

In [70]:
# load the grouped_df
grouped_df = pd.read_csv("./linear_regression_suite/results/coati_linear_probing_grouped.csv")

# add a column rank_rmse
grouped_df['rank_rmse'] = grouped_df.groupby('Dataset')['RMSE'].rank(ascending=True)

# add a column rank_spearman
grouped_df['rank_spearman'] = grouped_df.groupby('Dataset')['Spearman'].rank(ascending=False)

# add a column rank_davgp
grouped_df['rank_davgp'] = grouped_df.groupby('Dataset')['davgp'].rank(ascending=False)

grouped_df['rank_auroc'] = grouped_df.groupby('Dataset')['AUROC Score'].rank(ascending=False)

grouped_df

,Dataset,Model,AUROC Score,AUROC std,RMSE,Spearman,avgp,avgp_std,davgp,davgp_std,rank_rmse,rank_spearman,rank_davgp,rank_auroc
0,ames,Autoreg Only,0.622710,0.007784,NaN,NaN,0.617710,0.009906,0.077425,0.005897,NaN,NaN,5.0,5.0
1,ames,Barlow Closed (Text),0.705771,0.007628,NaN,NaN,0.682496,0.009607,0.142211,0.006744,NaN,NaN,3.0,3.0
2,ames,CLAMP,0.729509,0.007313,NaN,NaN,0.702198,0.009492,0.161914,0.007049,NaN,NaN,1.0,1.0
3,ames,Grande Closed (Text),0.664600,0.007736,NaN,NaN,0.649511,0.009716,0.109226,0.006399,NaN,NaN,4.0,4.0
4,ames,coati2,0.729429,0.007428,NaN,NaN,0.699742,0.009315,0.159458,0.006912,NaN,NaN,2.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99,vdss_lombardo,Autoreg Only,NaN,NaN,NaN,0.131986,NaN,NaN,NaN,NaN,NaN,5.0,NaN,NaN
100,vdss_lombardo,Barlow Closed (Text),NaN,NaN,NaN,0.344879,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN
101,vdss_lombardo,CLAMP,NaN,NaN,NaN,0.504836,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN
102,vdss_lombardo,Grande Closed (Text),NaN,NaN,NaN,0.397382,NaN,NaN,NaN,NaN,NaN,3.0,NaN,NaN
103,vdss_lombardo,coati2,NaN,NaN,NaN,0.454551,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN

In [71]:
# average over all ranks per model
grouped_by_model = grouped_df.groupby('Model').mean(numeric_only=True).reset_index()
grouped_by_model

,Model,AUROC Score,AUROC std,RMSE,Spearman,avgp,avgp_std,davgp,davgp_std,rank_rmse,rank_spearman,rank_davgp,rank_auroc
0,Autoreg Only,0.638286,0.019989,4.256608,0.150052,0.548292,0.017408,0.070818,0.011071,4.8,5.00,4.916667,4.666667
1,Barlow Closed (Text),0.722919,0.018666,4.008301,0.303314,0.612543,0.017475,0.135143,0.013342,3.4,3.50,2.916667,3.083333
2,CLAMP,0.744062,0.018244,3.672209,0.315929,0.633190,0.017534,0.155789,0.013673,3.2,3.00,2.166667,2.333333
3,Grande Closed (Text),0.713531,0.018882,3.851035,0.359773,0.604421,0.017034,0.127020,0.012772,2.2,1.75,3.416667,3.333333
4,coati2,0.744052,0.018164,3.675406,0.361294,0.630782,0.018065,0.153381,0.014637,1.4,1.75,1.583333,1.583333

In [72]:
# mean of rankg_rmse and rank_spearman
grouped_by_model['regression_rank'] = grouped_by_model[['rank_rmse', 'rank_spearman']].mean(axis=1)
grouped_by_model

,Model,AUROC Score,AUROC std,RMSE,Spearman,avgp,avgp_std,davgp,davgp_std,rank_rmse,rank_spearman,rank_davgp,rank_auroc,regression_rank
0,Autoreg Only,0.638286,0.019989,4.256608,0.150052,0.548292,0.017408,0.070818,0.011071,4.8,5.00,4.916667,4.666667,4.900
1,Barlow Closed (Text),0.722919,0.018666,4.008301,0.303314,0.612543,0.017475,0.135143,0.013342,3.4,3.50,2.916667,3.083333,3.450
2,CLAMP,0.744062,0.018244,3.672209,0.315929,0.633190,0.017534,0.155789,0.013673,3.2,3.00,2.166667,2.333333,3.100
3,Grande Closed (Text),0.713531,0.018882,3.851035,0.359773,0.604421,0.017034,0.127020,0.012772,2.2,1.75,3.416667,3.333333,1.975
4,coati2,0.744052,0.018164,3.675406,0.361294,0.630782,0.018065,0.153381,0.014637,1.4,1.75,1.583333,1.583333,1.575

In [73]:
# deleted columns AURCO Score, RMSE, Spearman, avgp, davg, davgp, davgp_std
grouped_by_model = grouped_by_model.drop(columns=['AUROC Score', 'AUROC std', 'RMSE', 'Spearman', 'avgp', 'avgp_std', 'davgp', 'davgp_std'])
grouped_by_model

,Model,rank_rmse,rank_spearman,rank_davgp,rank_auroc,regression_rank
0,Autoreg Only,4.8,5.00,4.916667,4.666667,4.900
1,Barlow Closed (Text),3.4,3.50,2.916667,3.083333,3.450
2,CLAMP,3.2,3.00,2.166667,2.333333,3.100
3,Grande Closed (Text),2.2,1.75,3.416667,3.333333,1.975
4,coati2,1.4,1.75,1.583333,1.583333,1.575

In [37]:
grouped_by_model

,Model,AUROC std,avgp_std,rank_auroc,rank_rmse,rank_spearman,rank_davgp,avg_rank,regression_rank
0,Autoreg Only,0.019989,0.017408,4.666667,4.8,5.00,1.083333,3.675000,4.900
1,Barlow Closed (Text),0.018666,0.017475,3.083333,3.4,3.50,3.083333,3.238095,3.450
2,CLAMP,0.018244,0.017534,2.333333,3.2,3.00,3.833333,3.095238,3.100
3,Grande Closed (Text),0.018882,0.017034,3.333333,2.2,1.75,2.583333,2.547619,1.975
4,coati2,0.018164,0.018065,1.583333,1.4,1.75,4.416667,2.380952,1.575

In [74]:
# delete column AUROC std
grouped_by_model = grouped_by_model.drop(columns=['AUROC std'])
grouped_by_model

KeyError: "['AUROC std'] not found in axis"

In [75]:
# to csv
grouped_by_model.to_csv("coati_linear_probing_ranks.csv", index=False)

In [60]:
# read csv as pandas and convert it to a table for latex
import pandas as pd

df = pd.read_csv("./linear_regression_suite/results/coati_linear_probing_grouped.csv")
df

,Dataset,Model,AUROC Score,AUROC std,RMSE,Spearman,avgp,avgp_std,davgp,davgp_std
0,ames,Autoreg Only,0.622710,0.007784,NaN,NaN,0.617710,0.009906,0.077425,0.005897
1,ames,Barlow Closed (Text),0.705771,0.007628,NaN,NaN,0.682496,0.009607,0.142211,0.006744
2,ames,CLAMP,0.729509,0.007313,NaN,NaN,0.702198,0.009492,0.161914,0.007049
3,ames,Grande Closed (Text),0.664600,0.007736,NaN,NaN,0.649511,0.009716,0.109226,0.006399
4,ames,coati2,0.729429,0.007428,NaN,NaN,0.699742,0.009315,0.159458,0.006912
...,...,...,...,...,...,...,...,...,...,...
99,vdss_lombardo,Autoreg Only,NaN,NaN,NaN,0.131986,NaN,NaN,NaN,NaN
100,vdss_lombardo,Barlow Closed (Text),NaN,NaN,NaN,0.344879,NaN,NaN,NaN,NaN
101,vdss_lombardo,CLAMP,NaN,NaN,NaN,0.504836,NaN,NaN,NaN,NaN
102,vdss_lombardo,Grande Closed (Text),NaN,NaN,NaN,0.397382,NaN,NaN,NaN,NaN
103,vdss_lombardo,coati2,NaN,NaN,NaN,0.454551,NaN,NaN,NaN,NaN

In [56]:
# remove all rows in which RMSE OR Spearman is NaN
df.dropna(subset=['RMSE', 'Spearman'], how='all', inplace=True)
df

,Dataset,Model,AUROC Score,AUROC std,RMSE,Spearman,avgp,avgp_std,davgp,davgp_std
10,bace_regression,Autoreg Only,NaN,NaN,0.776282,NaN,NaN,NaN,NaN,NaN
11,bace_regression,Barlow Closed (Text),NaN,NaN,0.717574,NaN,NaN,NaN,NaN,NaN
12,bace_regression,CLAMP,NaN,NaN,0.823627,NaN,NaN,NaN,NaN,NaN
13,bace_regression,Grande Closed (Text),NaN,NaN,0.693536,NaN,NaN,NaN,NaN,NaN
14,bace_regression,coati2,NaN,NaN,0.703722,NaN,NaN,NaN,NaN,NaN
20,caco2_wang,Autoreg Only,NaN,NaN,0.709149,NaN,NaN,NaN,NaN,NaN
21,caco2_wang,Barlow Closed (Text),NaN,NaN,0.617643,NaN,NaN,NaN,NaN,NaN
22,caco2_wang,CLAMP,NaN,NaN,0.662857,NaN,NaN,NaN,NaN,NaN
23,caco2_wang,Grande Closed (Text),NaN,NaN,0.579792,NaN,NaN,NaN,NaN,NaN
24,caco2_wang,coati2,NaN,NaN,0.543222,NaN,NaN,NaN,NaN,NaN
25,clearance_hepatocyte_az,Autoreg Only,NaN,NaN,NaN,0.138797,NaN,NaN,NaN,NaN
26,clearance_hepatocyte_az,Barlow Closed (Text),NaN,NaN,NaN,0.317557,NaN,NaN,NaN,NaN
27,clearance_hepatocyte_az,CLAMP,NaN,NaN,NaN,0.271182,NaN,NaN,NaN,NaN
28,clearance_hepatocyte_az,Grande Closed (Text),NaN,NaN,NaN,0.339012,NaN,NaN,NaN,NaN
29,clearance_hepatocyte_az,coati2,NaN,NaN,NaN,0.374097,NaN,NaN,NaN,NaN
30,clearance_microsome_az,Autoreg Only,NaN,NaN,NaN,0.179373,NaN,NaN,NaN,NaN
31,clearance_microsome_az,Barlow Closed (Text),NaN,NaN,NaN,0.402265,NaN,NaN,NaN,NaN
32,clearance_microsome_az,CLAMP,NaN,NaN,NaN,0.335783,NaN,NaN,NaN,NaN
33,clearance_microsome_az,Grande Closed (Text),NaN,NaN,NaN,0.460465,NaN,NaN,NaN,NaN
34,clearance_microsome_az,coati2,NaN,NaN,NaN,0.445369,NaN,NaN,NaN,NaN
50,delaney,Autoreg Only,NaN,NaN,0.834461,NaN,NaN,NaN,NaN,NaN
51,delaney,Barlow Closed (Text),NaN,NaN,0.742513,NaN,NaN,NaN,NaN,NaN
52,delaney,CLAMP,NaN,NaN,0.642683,NaN,NaN,NaN,NaN,NaN
53,delaney,Grande Closed (Text),NaN,NaN,0.644970,NaN,NaN,NaN,NaN,NaN
54,delaney,coati2,NaN,NaN,0.607177,NaN,NaN,NaN,NaN,NaN
60,half_life_obach,Barlow Closed (Text),NaN,NaN,NaN,0.148554,NaN,NaN,NaN,NaN
61,half_life_obach,CLAMP,NaN,NaN,NaN,0.151914,NaN,NaN,NaN,NaN
62,half_life_obach,Grande Closed (Text),NaN,NaN,NaN,0.242232,NaN,NaN,NaN,NaN
63,half_life_obach,coati2,NaN,NaN,NaN,0.171160,NaN,NaN,NaN,NaN
84,ld50_zhu,Autoreg Only,NaN,NaN,0.841284,NaN,NaN,NaN,NaN,NaN
85,ld50_zhu,Barlow Closed (Text),NaN,NaN,0.794274,NaN,NaN,NaN,NaN,NaN
86,ld50_zhu,CLAMP,NaN,NaN,0.827834,NaN,NaN,NaN,NaN,NaN
87,ld50_zhu,Grande Closed (Text),NaN,NaN,0.790421,NaN,NaN,NaN,NaN,NaN
88,ld50_zhu,coati2,NaN,NaN,0.782710,NaN,NaN,NaN,NaN,NaN
94,ppbr_az,Autoreg Only,NaN,NaN,18.121862,NaN,NaN,NaN,NaN,NaN
95,ppbr_az,Barlow Closed (Text),NaN,NaN,17.169502,NaN,NaN,NaN,NaN,NaN
96,ppbr_az,CLAMP,NaN,NaN,15.404045,NaN,NaN,NaN,NaN,NaN
97,ppbr_az,Grande Closed (Text),NaN,NaN,16.546454,NaN,NaN,NaN,NaN,NaN
98,ppbr_az,coati2,NaN,NaN,15.740199,NaN,NaN,NaN,NaN,NaN
99,vdss_lombardo,Autoreg Only,NaN,NaN,NaN,0.131986,NaN,NaN,NaN,NaN
100,vdss_lombardo,Barlow Closed (Text),NaN,NaN,NaN,0.344879,NaN,NaN,NaN,NaN
101,vdss_lombardo,CLAMP,NaN,NaN,NaN,0.504836,NaN,NaN,NaN,NaN
102,vdss_lombardo,Grande Closed (Text),NaN,NaN,NaN,0.397382,NaN,NaN,NaN,NaN
103,vdss_lombardo,coati2,NaN,NaN,NaN,0.454551,NaN,NaN,NaN,NaN

In [61]:
import pandas as pd
import numpy as np

# Assuming df is your DataFrame loaded from the CSV

df = pd.read_csv("./linear_regression_suite/results/coati_linear_probing_grouped.csv")

# Fill NaN values for RMSE with the Spearman values and vice versa
df['RMSE'] = df['RMSE'].fillna(df['Spearman'])
df['Spearman'] = df['Spearman'].fillna(df['RMSE'])

# Create a new column for the metric which checks if RMSE is NaN, if so, use 'Spearman', otherwise 'RMSE'
df['Metric'] = np.where(df['RMSE'].isna(), 'Spearman', 'RMSE')

# Select columns for the pivot and melt
df = df[['Dataset', 'Model', 'RMSE', 'Spearman', 'Metric']]

# Melt the DataFrame to get a long format
df_melted = df.melt(id_vars=['Dataset', 'Model', 'Metric'], value_vars=['RMSE', 'Spearman'], var_name='Metric_Type', value_name='Value')

# Filter out the unwanted metric values, keeping only the chosen metric per row
df_filtered = df_melted[df_melted['Metric'] == df_melted['Metric_Type']]

# Pivot to get the desired format
result = df_filtered.pivot_table(index=['Dataset', 'Metric'], columns='Model', values='Value', aggfunc='first').reset_index()

# Clean up the DataFrame to remove any multi-level column headers
result.columns.name = None
result.reset_index(drop=True, inplace=True)

# Print or save the transformed DataFrame
results

# Optionally, save to a new CSV
# result.to_csv('transformed_data.csv', index=False)

,Dataset,Seed,Analysis Type,Model,AUROC Score,AUROC std,RMSE,Spearman,avgp,avgp_std,davgp,davgp_std
0,ames,0,Classification,Barlow Closed (Text),0.716956,0.007467,NaN,NaN,0.700366,0.009978,0.151190,0.006749
1,ames,0,Classification,Grande Closed (Text),0.682680,0.007573,NaN,NaN,0.673720,0.009531,0.124544,0.006607
2,ames,0,Classification,CLAMP,0.743715,0.007206,NaN,NaN,0.720499,0.009556,0.171323,0.006810
3,ames,0,Classification,coati2,0.744065,0.007250,NaN,NaN,0.721438,0.008904,0.172262,0.006390
4,ames,1,Classification,Barlow Closed (Text),0.698516,0.007720,NaN,NaN,0.685105,0.009864,0.136328,0.006472
...,...,...,...,...,...,...,...,...,...,...,...,...
1043,half_life_obach,8,Regression,coati2,NaN,NaN,NaN,0.221459,NaN,NaN,NaN,NaN
1044,half_life_obach,9,Regression,Barlow Closed (Text),NaN,NaN,NaN,0.183688,NaN,NaN,NaN,NaN
1045,half_life_obach,9,Regression,Grande Closed (Text),NaN,NaN,NaN,0.203125,NaN,NaN,NaN,NaN
1046,half_life_obach,9,Regression,CLAMP,NaN,NaN,NaN,0.311776,NaN,NaN,NaN,NaN
1047,half_life_obach,9,Regression,coati2,NaN,NaN,NaN,0.209550,NaN,NaN,NaN,NaN